[project]
name = "lelamp-runtime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "adafruit-circuitpython-neopixel",
    "feetech-servo-sdk>=1.0.0",
    "lerobot>=0.3.3",
    "numpy>=2.2.6",
    "rpi-ws281x",
    "sounddevice>=0.5.2",
]
